# Generated by Django 2.2.5 on 2019-12-22 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 12, 22, 18, 49, 1, 750163, tzinfo=utc), verbose_name='time')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
