# Generated by Django 3.0.5 on 2020-05-19 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_remove_city_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 3, 4, 17, 957106, tzinfo=utc)),
        ),
    ]
